### PR TITLE
Add the ASCII function for SQLServer

### PR DESCRIPTION
**Pull request by tnicolas29200**
Hello,

I do not know if you plan to do specific implementations for DBMS, here is an implementation of a very simple function (ASCII) for SQLServer.

If it suits you, I can implement others for SQLServer and MySQL to make the library more complete

### CODE REVIEW

**Comment by jeffgbutler** [comment]
At this point, I am only interested in SQL standard functions.  I am trying not to put anything DB specific in this library.

Anything that is specific to SQL server should be in your project - or perhaps a separate library.

**Comment by tnicolas29200** [comment]
I understand your point of view, even if I find it a pity not to propose specificities by DBMS: limit to the standard SQL flanges the library.

**Comment by jeffgbutler** [comment]
I'll write something about what kinds of contributions I'm looking for add it to the documentation.  But one thing I can say now - I am not trying to duplicate every possible SQL function or capability in this library.  Think of this library as a framework where you could add specific capabilities as needed for your project.

You can create as many functions as you need for your project, and they can be very specific to your need, but they don't all need to be added to the base code.  I think of the existing functions in the library more like examples that can use to build your own extensions.  So, for example, I don't want to end up with implementation classes for all of the hundreds of SQL functions that exist.

I AM interested in changes to the library that might enable you to do things you can't do now through some existing extension mechanism. If you find something like that, then I would welcome a contribution.

**Comment by jeffgbutler** [comment]
Closing because this is only for SQL server.

**Pull request closed without merging**
