### PR TITLE
Remove Travis in favor of GitHub Actions

### PR DESCRIPTION
**Pull request by jeffgbutler**
@hazendaz what do you think about just removing Travis? Everything is working now in GitHub actions. I noticed that you left Travis in some of the other repos because of Coveralls, but I have Coveralls working with GitHub actions too (albeit it's a little clunky right now).

### CODE REVIEW

**Comment by hazendaz** [comment]
@jeffgbutler Yup that was the plan once everything was ported over.  Some projects were much more close and ready 👍

**Comment by hazendaz** [comment]
@jeffgbutler Only thing on this that was different than others was use of docker on travis but if all good, that was my only real question.  The 'site' that has been ever commented out I have a working solution that makes that work but takes a bit more configuration to pull off.  I will cycle back through to gain that benefit.  That is just mroe useful when we don't release often and may not be necessary everywhere.

**Comment by hazendaz** [comment]
@jeffgbutler Cool on the coveralls, I'll check out what you did.  We talked a bit about that on slack.  The one that is probably not so clunky is codecov but from some testing that was done previously it looked like that was not god for the PRs (too much data).

**Comment by jeffgbutler** [comment]
@hazendaz thanks! I always forget you guys are available on Slack.

**Pull request merged**
